# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e582797c6254a1dd772f0f9f48da854"
name = "Alpha"
handle = "alpha-29"
application_url = "https://79bb-111-88-11-20.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://79bb-111-88-11-20.ngrok-free.app/auth/callback", "https://79bb-111-88-11-20.ngrok-free.app/auth/shopify/callback", "https://79bb-111-88-11-20.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
